apiVersion: fn.kpt.dev/v1alpha1
kind: Fleet
metadata:
  name: example-fleet
spec:

  upstreams:
  - name: example
    type: git
    git:
      repo: https://github.com/krm-functions/catalog

  # These settings can also be given individually for each package
  defaults:
    upstream: example
    enabled: true
    ref: main

  packages:
  - name: foo
    sourcePath: examples/package-composer/pkg1
  - name: bar
    sourcePath: examples/package-composer/pkg2
    packages:
    - name: baz1
      sourcePath: examples/package-composer/pkg3
    - name: baz2
      sourcePath: examples/package-composer/pkg1
  - name: olo
    stub: true
    packages:
    - name: baz
      sourcePath: examples/package-composer/pkg4
  - name: boo
    enabled: false
    sourcePath: examples/package-composer/pkg1
