apiVersion: fn.kpt.dev/v1alpha1
kind: RenderHelmChart
metadata:
  name: render-chart
  annotations:
    config.kubernetes.io/local-config: "true"
    experimental.helm.sh/upgrade-constraint: "<=4.10.0"
helmCharts:
- chartArgs:
    name: metacontroller-helm
    version: v4.4.0
    repo: oci://ghcr.io/metacontroller
  templateOptions:
    releaseName: metacontroller
    namespace: metacontroller
