apiVersion: v1
kind: ConfigMap
metadata:
  name: valid
data:
  foo: bar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: invalid-nested-dict
data:
  nested:
    bar: baz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: invalid-non-string-value
data:
  a-number: 42
