apiVersion: foo.bar
kind: Fleet
metadata:
  name: example-fleet
spec:

  # These settings can also be given individually for each package
  defaults:
    upstream:
      type: git
      git:
        repo: https://github.com/krm-functions/catalog.git
        ref: feature/source-packages-function # kpt-set: ${defaultRef}
    enabled: true

  packages:
  - name: foo
    sourcePath: examples/source-packages/pkg1
  - name: bar
    sourcePath: examples/source-packages/pkg2
    packages:
    - name: baz
      sourcePath: examples/source-packages/pkg3
  - name: olo
    stub: true
    packages:
    - name: baz
      sourcePath: examples/source-packages/pkg4
