apiVersion: fn.kpt.dev/v1alpha1
kind: RenderHelmChart
metadata:
  name: render-chart
  annotations:
    config.kubernetes.io/local-config: "true"
helmCharts:
- chartArgs:
    name: cert-manager
    version: v1.12.2
    repo: https://charts.jetstack.io
  templateOptions:
    releaseName: cert-managerrel
    namespace: cert-managerns
    values:
      valuesInline:
        global:
          commonLabels:
            team_name: dev  # kpt-set: ${teamName}
        image:
          digest: ""   # digester: quay.io/jetstack/cert-manager-controller:.*
        webhook:
          image:
            digest: "" # digester: quay.io/jetstack/cert-manager-webhook:.*
        cainjector:
          image:
            digest: "" # digester: quay.io/jetstack/cert-manager-cainjector:.*
        startupapicheck:
          image:
            digest: "" # digester: quay.io/jetstack/cert-manager-ctl:.*
