name: Run lint

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request ]
    paths-ignore:
      - 'README.md'

jobs:
  lint:
    strategy:
      matrix:
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Lint
      run: make lint
