name: Run lint

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'scripts/**'
      - 'docs/**'

jobs:
  lint:
    strategy:
      matrix:
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Lint
      run: make lint
