name: Run tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'scripts/**'
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: build local binaries for test
      run: make build lint test

    - name: install kpt
      run: |
        curl -sLO https://github.com/GoogleContainerTools/kpt/releases/download/v1.0.0-beta.38/kpt_linux_amd64-1.0.0-beta.38.tar.gz
        tar -xzf kpt_linux_amd64-1.0.0-beta.38.tar.gz
        mv kpt /usr/local/bin/

    - name: code tests
      run: make test GOFLAGS="-v"

    - name: e2e tests
      run: make e2e-tests
